### ISSUE TITLE
1.20 Issues

### ISSUE THREAD

**Issue by Tifffy** [Maazapan/UltraMailBox-Wiki#5]
1.20 does not work at all, even though spigot says it is compatible with 1.20. I have even tried using an older version to carry across the files. We have added the jar fine but it wouldn't then add the config files to our server on 1.20. As I mentioned we tried then adding the plugin on an older version to get the file, and have added that to the 1.20 world, still nothing working in game, no commands work no nothing. I totally understand and hope this is just a new bug, but reading a review now I am a little worried that the plugin is in fact not 1.20 supported even though spigot says it is and that I have paid money for a falsely advertised plugin which yeah wouldn't be great and might need investigating. If someone could maybe contact here and help with this bug before I contact spigot directly that would be totally amazing! Hopefully it will be an easy fix, thank you!

**Comment by Maazapan** [comment]
Hello, the update fixing that was already uploaded
